# Generated by Django 2.0.7 on 2018-08-20 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
